version: '3.7'
services:
  waf:
    build:
     context: contrib
     dockerfile: Dockerfile.fedora33
    image: mvilche/modsecurity:fedora33-v3.3.0
    environment:
     - SERVERNAME=sitio.com.uy
     - PROXY_IP=ablepharuslit.myspecies.info
     - PROXY_PORT=80
     - PROTOCOL_PROXY=http
     - MODSECURITY_STATUS=On
    ports:
     - "443:8443"
