version: '3.7'
services:
  waf:
    build:
     context: contrib
     dockerfile: Dockerfile.centos8
    image: mvilche/modsecurity:centos8-v3.3.0
    environment:
     - SERVERNAME=domain.example
     - PROXY_IP=127.0.0.1
     - PROXY_PORT=80
     - PROTOCOL_PROXY=http
     - MODSECURITY_STATUS=On
    ports:
     - "8443:8443"
