version: '3.7'
services:
  waf:
    image: mvilche/modsecurity:fedora33-v3.3.0
    environment:
     - SERVERNAME=sitio.com.uy
     - PROXY_IP=172.17.0.3
     - PROXY_PORT=8080
     - PROTOCOL_PROXY=http
     - MODSECURITY_STATUS=Off
    ports:
     - "8443:8443"
